spring.application.name=spring-ai-dbt
##OpenAI
#spring.ai.openai.api-key=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
#spring.ai.openai.api-key=sk-c7bf5b4f3c77472da5c1b0090d4499b3
#spring.ai.openai.base-url=api.deepseek.com
#spring.ai.openai.chat.options.model=deepseek-chat

## Ollama - local
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
#spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.init.pull-model-strategy=when_missing

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=admin
spring.datasource.password=